# Generated by Django 4.2 on 2023-04-17 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='cedula',
            field=models.CharField(default=datetime.datetime(2023, 4, 17, 19, 52, 20, 817739), max_length=8),
            preserve_default=False,
        ),
    ]
