# Generated by Django 4.2 on 2023-05-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('control_asistencia', '0003_docente_estudiante_materia_delete_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='groups',
            field=models.ManyToManyField(default=['Grupo_DOCENTES'], related_name='docente_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='groups',
            field=models.ManyToManyField(default=['Grupo_ESTUDIANTES'], related_name='estudiante_groups', to='auth.group'),
        ),
    ]
