# Generated by Django 4.2 on 2023-05-12 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_asistencia', '0004_alter_docente_groups_alter_estudiante_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiasDocente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materia',
            name='estudiantes',
            field=models.ManyToManyField(related_name='materiasEstudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
