# Generated by Django 4.2 on 2023-05-13 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('control_asistencia', '0006_alter_materia_docente_alter_materia_estudiantes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='control_asistencia.materia')),
            ],
        ),
    ]
